# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - docker-hub-creds

jobs:
  build:
    docker:
      - image: mbedos/mbed-os-env-armc:latest
        auth:
          username: mbedos
          password: $DOCKERHUB_PASSWORD
    working_directory: ~
    steps:
      - checkout:
          path: mbed-os-example-blinky
      - run: |
          cd mbed-os-example-blinky
          mbed deploy
          mbed compile -t ARM -m K64F
